repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: 9a9bbc00895bbdb7670231c2565d4f1309c42905  # SHA of v1.3.5
    hooks:
      - id: cpplint
      - id: cppcheck
      - id: clang-format
