# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/valentin/Escritorio/Programas/Worms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/valentin/Escritorio/Programas/Worms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/valentin/Escritorio/Programas/Worms/CMakeFiles /home/valentin/Escritorio/Programas/Worms//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/valentin/Escritorio/Programas/Worms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named editor

# Build rule for target.
editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 editor
.PHONY : editor

# fast build rule for target.
editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/build
.PHONY : editor/fast

level_editor/file_editor.o: level_editor/file_editor.cpp.o
.PHONY : level_editor/file_editor.o

# target to build an object file
level_editor/file_editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/file_editor.cpp.o
.PHONY : level_editor/file_editor.cpp.o

level_editor/file_editor.i: level_editor/file_editor.cpp.i
.PHONY : level_editor/file_editor.i

# target to preprocess a source file
level_editor/file_editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/file_editor.cpp.i
.PHONY : level_editor/file_editor.cpp.i

level_editor/file_editor.s: level_editor/file_editor.cpp.s
.PHONY : level_editor/file_editor.s

# target to generate assembly for a file
level_editor/file_editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/file_editor.cpp.s
.PHONY : level_editor/file_editor.cpp.s

level_editor/level_editor.o: level_editor/level_editor.cpp.o
.PHONY : level_editor/level_editor.o

# target to build an object file
level_editor/level_editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/level_editor.cpp.o
.PHONY : level_editor/level_editor.cpp.o

level_editor/level_editor.i: level_editor/level_editor.cpp.i
.PHONY : level_editor/level_editor.i

# target to preprocess a source file
level_editor/level_editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/level_editor.cpp.i
.PHONY : level_editor/level_editor.cpp.i

level_editor/level_editor.s: level_editor/level_editor.cpp.s
.PHONY : level_editor/level_editor.s

# target to generate assembly for a file
level_editor/level_editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/level_editor.cpp.s
.PHONY : level_editor/level_editor.cpp.s

level_editor/lobby.o: level_editor/lobby.cpp.o
.PHONY : level_editor/lobby.o

# target to build an object file
level_editor/lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/lobby.cpp.o
.PHONY : level_editor/lobby.cpp.o

level_editor/lobby.i: level_editor/lobby.cpp.i
.PHONY : level_editor/lobby.i

# target to preprocess a source file
level_editor/lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/lobby.cpp.i
.PHONY : level_editor/lobby.cpp.i

level_editor/lobby.s: level_editor/lobby.cpp.s
.PHONY : level_editor/lobby.s

# target to generate assembly for a file
level_editor/lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/lobby.cpp.s
.PHONY : level_editor/lobby.cpp.s

level_editor/main.o: level_editor/main.cpp.o
.PHONY : level_editor/main.o

# target to build an object file
level_editor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/main.cpp.o
.PHONY : level_editor/main.cpp.o

level_editor/main.i: level_editor/main.cpp.i
.PHONY : level_editor/main.i

# target to preprocess a source file
level_editor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/main.cpp.i
.PHONY : level_editor/main.cpp.i

level_editor/main.s: level_editor/main.cpp.s
.PHONY : level_editor/main.s

# target to generate assembly for a file
level_editor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/main.cpp.s
.PHONY : level_editor/main.cpp.s

level_editor/position_converter.o: level_editor/position_converter.cpp.o
.PHONY : level_editor/position_converter.o

# target to build an object file
level_editor/position_converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/position_converter.cpp.o
.PHONY : level_editor/position_converter.cpp.o

level_editor/position_converter.i: level_editor/position_converter.cpp.i
.PHONY : level_editor/position_converter.i

# target to preprocess a source file
level_editor/position_converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/position_converter.cpp.i
.PHONY : level_editor/position_converter.cpp.i

level_editor/position_converter.s: level_editor/position_converter.cpp.s
.PHONY : level_editor/position_converter.s

# target to generate assembly for a file
level_editor/position_converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/position_converter.cpp.s
.PHONY : level_editor/position_converter.cpp.s

level_editor/world.o: level_editor/world.cpp.o
.PHONY : level_editor/world.o

# target to build an object file
level_editor/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/world.cpp.o
.PHONY : level_editor/world.cpp.o

level_editor/world.i: level_editor/world.cpp.i
.PHONY : level_editor/world.i

# target to preprocess a source file
level_editor/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/world.cpp.i
.PHONY : level_editor/world.cpp.i

level_editor/world.s: level_editor/world.cpp.s
.PHONY : level_editor/world.s

# target to generate assembly for a file
level_editor/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/level_editor/world.cpp.s
.PHONY : level_editor/world.cpp.s

src/client/client_beam.o: src/client/client_beam.cpp.o
.PHONY : src/client/client_beam.o

# target to build an object file
src/client/client_beam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_beam.cpp.o
.PHONY : src/client/client_beam.cpp.o

src/client/client_beam.i: src/client/client_beam.cpp.i
.PHONY : src/client/client_beam.i

# target to preprocess a source file
src/client/client_beam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_beam.cpp.i
.PHONY : src/client/client_beam.cpp.i

src/client/client_beam.s: src/client/client_beam.cpp.s
.PHONY : src/client/client_beam.s

# target to generate assembly for a file
src/client/client_beam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_beam.cpp.s
.PHONY : src/client/client_beam.cpp.s

src/client/client_client.o: src/client/client_client.cpp.o
.PHONY : src/client/client_client.o

# target to build an object file
src/client/client_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_client.cpp.o
.PHONY : src/client/client_client.cpp.o

src/client/client_client.i: src/client/client_client.cpp.i
.PHONY : src/client/client_client.i

# target to preprocess a source file
src/client/client_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_client.cpp.i
.PHONY : src/client/client_client.cpp.i

src/client/client_client.s: src/client/client_client.cpp.s
.PHONY : src/client/client_client.s

# target to generate assembly for a file
src/client/client_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_client.cpp.s
.PHONY : src/client/client_client.cpp.s

src/client/client_explosion.o: src/client/client_explosion.cpp.o
.PHONY : src/client/client_explosion.o

# target to build an object file
src/client/client_explosion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_explosion.cpp.o
.PHONY : src/client/client_explosion.cpp.o

src/client/client_explosion.i: src/client/client_explosion.cpp.i
.PHONY : src/client/client_explosion.i

# target to preprocess a source file
src/client/client_explosion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_explosion.cpp.i
.PHONY : src/client/client_explosion.cpp.i

src/client/client_explosion.s: src/client/client_explosion.cpp.s
.PHONY : src/client/client_explosion.s

# target to generate assembly for a file
src/client/client_explosion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_explosion.cpp.s
.PHONY : src/client/client_explosion.cpp.s

src/client/client_lobby.o: src/client/client_lobby.cpp.o
.PHONY : src/client/client_lobby.o

# target to build an object file
src/client/client_lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_lobby.cpp.o
.PHONY : src/client/client_lobby.cpp.o

src/client/client_lobby.i: src/client/client_lobby.cpp.i
.PHONY : src/client/client_lobby.i

# target to preprocess a source file
src/client/client_lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_lobby.cpp.i
.PHONY : src/client/client_lobby.cpp.i

src/client/client_lobby.s: src/client/client_lobby.cpp.s
.PHONY : src/client/client_lobby.s

# target to generate assembly for a file
src/client/client_lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_lobby.cpp.s
.PHONY : src/client/client_lobby.cpp.s

src/client/client_main.o: src/client/client_main.cpp.o
.PHONY : src/client/client_main.o

# target to build an object file
src/client/client_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.cpp.o
.PHONY : src/client/client_main.cpp.o

src/client/client_main.i: src/client/client_main.cpp.i
.PHONY : src/client/client_main.i

# target to preprocess a source file
src/client/client_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.cpp.i
.PHONY : src/client/client_main.cpp.i

src/client/client_main.s: src/client/client_main.cpp.s
.PHONY : src/client/client_main.s

# target to generate assembly for a file
src/client/client_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.cpp.s
.PHONY : src/client/client_main.cpp.s

src/client/client_missile.o: src/client/client_missile.cpp.o
.PHONY : src/client/client_missile.o

# target to build an object file
src/client/client_missile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_missile.cpp.o
.PHONY : src/client/client_missile.cpp.o

src/client/client_missile.i: src/client/client_missile.cpp.i
.PHONY : src/client/client_missile.i

# target to preprocess a source file
src/client/client_missile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_missile.cpp.i
.PHONY : src/client/client_missile.cpp.i

src/client/client_missile.s: src/client/client_missile.cpp.s
.PHONY : src/client/client_missile.s

# target to generate assembly for a file
src/client/client_missile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_missile.cpp.s
.PHONY : src/client/client_missile.cpp.s

src/client/client_protocol.o: src/client/client_protocol.cpp.o
.PHONY : src/client/client_protocol.o

# target to build an object file
src/client/client_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_protocol.cpp.o
.PHONY : src/client/client_protocol.cpp.o

src/client/client_protocol.i: src/client/client_protocol.cpp.i
.PHONY : src/client/client_protocol.i

# target to preprocess a source file
src/client/client_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_protocol.cpp.i
.PHONY : src/client/client_protocol.cpp.i

src/client/client_protocol.s: src/client/client_protocol.cpp.s
.PHONY : src/client/client_protocol.s

# target to generate assembly for a file
src/client/client_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_protocol.cpp.s
.PHONY : src/client/client_protocol.cpp.s

src/client/client_receiver_thread.o: src/client/client_receiver_thread.cpp.o
.PHONY : src/client/client_receiver_thread.o

# target to build an object file
src/client/client_receiver_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_receiver_thread.cpp.o
.PHONY : src/client/client_receiver_thread.cpp.o

src/client/client_receiver_thread.i: src/client/client_receiver_thread.cpp.i
.PHONY : src/client/client_receiver_thread.i

# target to preprocess a source file
src/client/client_receiver_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_receiver_thread.cpp.i
.PHONY : src/client/client_receiver_thread.cpp.i

src/client/client_receiver_thread.s: src/client/client_receiver_thread.cpp.s
.PHONY : src/client/client_receiver_thread.s

# target to generate assembly for a file
src/client/client_receiver_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_receiver_thread.cpp.s
.PHONY : src/client/client_receiver_thread.cpp.s

src/client/client_resource_pool.o: src/client/client_resource_pool.cpp.o
.PHONY : src/client/client_resource_pool.o

# target to build an object file
src/client/client_resource_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_resource_pool.cpp.o
.PHONY : src/client/client_resource_pool.cpp.o

src/client/client_resource_pool.i: src/client/client_resource_pool.cpp.i
.PHONY : src/client/client_resource_pool.i

# target to preprocess a source file
src/client/client_resource_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_resource_pool.cpp.i
.PHONY : src/client/client_resource_pool.cpp.i

src/client/client_resource_pool.s: src/client/client_resource_pool.cpp.s
.PHONY : src/client/client_resource_pool.s

# target to generate assembly for a file
src/client/client_resource_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_resource_pool.cpp.s
.PHONY : src/client/client_resource_pool.cpp.s

src/client/client_sender_thread.o: src/client/client_sender_thread.cpp.o
.PHONY : src/client/client_sender_thread.o

# target to build an object file
src/client/client_sender_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_sender_thread.cpp.o
.PHONY : src/client/client_sender_thread.cpp.o

src/client/client_sender_thread.i: src/client/client_sender_thread.cpp.i
.PHONY : src/client/client_sender_thread.i

# target to preprocess a source file
src/client/client_sender_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_sender_thread.cpp.i
.PHONY : src/client/client_sender_thread.cpp.i

src/client/client_sender_thread.s: src/client/client_sender_thread.cpp.s
.PHONY : src/client/client_sender_thread.s

# target to generate assembly for a file
src/client/client_sender_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_sender_thread.cpp.s
.PHONY : src/client/client_sender_thread.cpp.s

src/client/client_worldview.o: src/client/client_worldview.cpp.o
.PHONY : src/client/client_worldview.o

# target to build an object file
src/client/client_worldview.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_worldview.cpp.o
.PHONY : src/client/client_worldview.cpp.o

src/client/client_worldview.i: src/client/client_worldview.cpp.i
.PHONY : src/client/client_worldview.i

# target to preprocess a source file
src/client/client_worldview.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_worldview.cpp.i
.PHONY : src/client/client_worldview.cpp.i

src/client/client_worldview.s: src/client/client_worldview.cpp.s
.PHONY : src/client/client_worldview.s

# target to generate assembly for a file
src/client/client_worldview.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_worldview.cpp.s
.PHONY : src/client/client_worldview.cpp.s

src/client/client_worm.o: src/client/client_worm.cpp.o
.PHONY : src/client/client_worm.o

# target to build an object file
src/client/client_worm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_worm.cpp.o
.PHONY : src/client/client_worm.cpp.o

src/client/client_worm.i: src/client/client_worm.cpp.i
.PHONY : src/client/client_worm.i

# target to preprocess a source file
src/client/client_worm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_worm.cpp.i
.PHONY : src/client/client_worm.cpp.i

src/client/client_worm.s: src/client/client_worm.cpp.s
.PHONY : src/client/client_worm.s

# target to generate assembly for a file
src/client/client_worm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_worm.cpp.s
.PHONY : src/client/client_worm.cpp.s

src/common/lib/liberror.o: src/common/lib/liberror.cpp.o
.PHONY : src/common/lib/liberror.o

# target to build an object file
src/common/lib/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/liberror.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/liberror.cpp.o
.PHONY : src/common/lib/liberror.cpp.o

src/common/lib/liberror.i: src/common/lib/liberror.cpp.i
.PHONY : src/common/lib/liberror.i

# target to preprocess a source file
src/common/lib/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/liberror.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/liberror.cpp.i
.PHONY : src/common/lib/liberror.cpp.i

src/common/lib/liberror.s: src/common/lib/liberror.cpp.s
.PHONY : src/common/lib/liberror.s

# target to generate assembly for a file
src/common/lib/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/liberror.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/liberror.cpp.s
.PHONY : src/common/lib/liberror.cpp.s

src/common/lib/resolver.o: src/common/lib/resolver.cpp.o
.PHONY : src/common/lib/resolver.o

# target to build an object file
src/common/lib/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/resolver.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/resolver.cpp.o
.PHONY : src/common/lib/resolver.cpp.o

src/common/lib/resolver.i: src/common/lib/resolver.cpp.i
.PHONY : src/common/lib/resolver.i

# target to preprocess a source file
src/common/lib/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/resolver.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/resolver.cpp.i
.PHONY : src/common/lib/resolver.cpp.i

src/common/lib/resolver.s: src/common/lib/resolver.cpp.s
.PHONY : src/common/lib/resolver.s

# target to generate assembly for a file
src/common/lib/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/resolver.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/resolver.cpp.s
.PHONY : src/common/lib/resolver.cpp.s

src/common/lib/resolvererror.o: src/common/lib/resolvererror.cpp.o
.PHONY : src/common/lib/resolvererror.o

# target to build an object file
src/common/lib/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/resolvererror.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/resolvererror.cpp.o
.PHONY : src/common/lib/resolvererror.cpp.o

src/common/lib/resolvererror.i: src/common/lib/resolvererror.cpp.i
.PHONY : src/common/lib/resolvererror.i

# target to preprocess a source file
src/common/lib/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/resolvererror.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/resolvererror.cpp.i
.PHONY : src/common/lib/resolvererror.cpp.i

src/common/lib/resolvererror.s: src/common/lib/resolvererror.cpp.s
.PHONY : src/common/lib/resolvererror.s

# target to generate assembly for a file
src/common/lib/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/resolvererror.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/resolvererror.cpp.s
.PHONY : src/common/lib/resolvererror.cpp.s

src/common/lib/socket.o: src/common/lib/socket.cpp.o
.PHONY : src/common/lib/socket.o

# target to build an object file
src/common/lib/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/socket.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/socket.cpp.o
.PHONY : src/common/lib/socket.cpp.o

src/common/lib/socket.i: src/common/lib/socket.cpp.i
.PHONY : src/common/lib/socket.i

# target to preprocess a source file
src/common/lib/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/socket.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/socket.cpp.i
.PHONY : src/common/lib/socket.cpp.i

src/common/lib/socket.s: src/common/lib/socket.cpp.s
.PHONY : src/common/lib/socket.s

# target to generate assembly for a file
src/common/lib/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/lib/socket.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/lib/socket.cpp.s
.PHONY : src/common/lib/socket.cpp.s

src/server/baseball_bat_callback.o: src/server/baseball_bat_callback.cpp.o
.PHONY : src/server/baseball_bat_callback.o

# target to build an object file
src/server/baseball_bat_callback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/baseball_bat_callback.cpp.o
.PHONY : src/server/baseball_bat_callback.cpp.o

src/server/baseball_bat_callback.i: src/server/baseball_bat_callback.cpp.i
.PHONY : src/server/baseball_bat_callback.i

# target to preprocess a source file
src/server/baseball_bat_callback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/baseball_bat_callback.cpp.i
.PHONY : src/server/baseball_bat_callback.cpp.i

src/server/baseball_bat_callback.s: src/server/baseball_bat_callback.cpp.s
.PHONY : src/server/baseball_bat_callback.s

# target to generate assembly for a file
src/server/baseball_bat_callback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/baseball_bat_callback.cpp.s
.PHONY : src/server/baseball_bat_callback.cpp.s

src/server/bodies/beam_body.o: src/server/bodies/beam_body.cpp.o
.PHONY : src/server/bodies/beam_body.o

# target to build an object file
src/server/bodies/beam_body.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/beam_body.cpp.o
.PHONY : src/server/bodies/beam_body.cpp.o

src/server/bodies/beam_body.i: src/server/bodies/beam_body.cpp.i
.PHONY : src/server/bodies/beam_body.i

# target to preprocess a source file
src/server/bodies/beam_body.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/beam_body.cpp.i
.PHONY : src/server/bodies/beam_body.cpp.i

src/server/bodies/beam_body.s: src/server/bodies/beam_body.cpp.s
.PHONY : src/server/bodies/beam_body.s

# target to generate assembly for a file
src/server/bodies/beam_body.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/beam_body.cpp.s
.PHONY : src/server/bodies/beam_body.cpp.s

src/server/bodies/body.o: src/server/bodies/body.cpp.o
.PHONY : src/server/bodies/body.o

# target to build an object file
src/server/bodies/body.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/body.cpp.o
.PHONY : src/server/bodies/body.cpp.o

src/server/bodies/body.i: src/server/bodies/body.cpp.i
.PHONY : src/server/bodies/body.i

# target to preprocess a source file
src/server/bodies/body.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/body.cpp.i
.PHONY : src/server/bodies/body.cpp.i

src/server/bodies/body.s: src/server/bodies/body.cpp.s
.PHONY : src/server/bodies/body.s

# target to generate assembly for a file
src/server/bodies/body.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/body.cpp.s
.PHONY : src/server/bodies/body.cpp.s

src/server/bodies/missile_body.o: src/server/bodies/missile_body.cpp.o
.PHONY : src/server/bodies/missile_body.o

# target to build an object file
src/server/bodies/missile_body.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/missile_body.cpp.o
.PHONY : src/server/bodies/missile_body.cpp.o

src/server/bodies/missile_body.i: src/server/bodies/missile_body.cpp.i
.PHONY : src/server/bodies/missile_body.i

# target to preprocess a source file
src/server/bodies/missile_body.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/missile_body.cpp.i
.PHONY : src/server/bodies/missile_body.cpp.i

src/server/bodies/missile_body.s: src/server/bodies/missile_body.cpp.s
.PHONY : src/server/bodies/missile_body.s

# target to generate assembly for a file
src/server/bodies/missile_body.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/missile_body.cpp.s
.PHONY : src/server/bodies/missile_body.cpp.s

src/server/bodies/worm_body.o: src/server/bodies/worm_body.cpp.o
.PHONY : src/server/bodies/worm_body.o

# target to build an object file
src/server/bodies/worm_body.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/worm_body.cpp.o
.PHONY : src/server/bodies/worm_body.cpp.o

src/server/bodies/worm_body.i: src/server/bodies/worm_body.cpp.i
.PHONY : src/server/bodies/worm_body.i

# target to preprocess a source file
src/server/bodies/worm_body.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/worm_body.cpp.i
.PHONY : src/server/bodies/worm_body.cpp.i

src/server/bodies/worm_body.s: src/server/bodies/worm_body.cpp.s
.PHONY : src/server/bodies/worm_body.s

# target to generate assembly for a file
src/server/bodies/worm_body.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bodies/worm_body.cpp.s
.PHONY : src/server/bodies/worm_body.cpp.s

src/server/broadcaster.o: src/server/broadcaster.cpp.o
.PHONY : src/server/broadcaster.o

# target to build an object file
src/server/broadcaster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/broadcaster.cpp.o
.PHONY : src/server/broadcaster.cpp.o

src/server/broadcaster.i: src/server/broadcaster.cpp.i
.PHONY : src/server/broadcaster.i

# target to preprocess a source file
src/server/broadcaster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/broadcaster.cpp.i
.PHONY : src/server/broadcaster.cpp.i

src/server/broadcaster.s: src/server/broadcaster.cpp.s
.PHONY : src/server/broadcaster.s

# target to generate assembly for a file
src/server/broadcaster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/broadcaster.cpp.s
.PHONY : src/server/broadcaster.cpp.s

src/server/client_manager_thread.o: src/server/client_manager_thread.cpp.o
.PHONY : src/server/client_manager_thread.o

# target to build an object file
src/server/client_manager_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client_manager_thread.cpp.o
.PHONY : src/server/client_manager_thread.cpp.o

src/server/client_manager_thread.i: src/server/client_manager_thread.cpp.i
.PHONY : src/server/client_manager_thread.i

# target to preprocess a source file
src/server/client_manager_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client_manager_thread.cpp.i
.PHONY : src/server/client_manager_thread.cpp.i

src/server/client_manager_thread.s: src/server/client_manager_thread.cpp.s
.PHONY : src/server/client_manager_thread.s

# target to generate assembly for a file
src/server/client_manager_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client_manager_thread.cpp.s
.PHONY : src/server/client_manager_thread.cpp.s

src/server/contact_listener.o: src/server/contact_listener.cpp.o
.PHONY : src/server/contact_listener.o

# target to build an object file
src/server/contact_listener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/contact_listener.cpp.o
.PHONY : src/server/contact_listener.cpp.o

src/server/contact_listener.i: src/server/contact_listener.cpp.i
.PHONY : src/server/contact_listener.i

# target to preprocess a source file
src/server/contact_listener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/contact_listener.cpp.i
.PHONY : src/server/contact_listener.cpp.i

src/server/contact_listener.s: src/server/contact_listener.cpp.s
.PHONY : src/server/contact_listener.s

# target to generate assembly for a file
src/server/contact_listener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/contact_listener.cpp.s
.PHONY : src/server/contact_listener.cpp.s

src/server/explosion_callback.o: src/server/explosion_callback.cpp.o
.PHONY : src/server/explosion_callback.o

# target to build an object file
src/server/explosion_callback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/explosion_callback.cpp.o
.PHONY : src/server/explosion_callback.cpp.o

src/server/explosion_callback.i: src/server/explosion_callback.cpp.i
.PHONY : src/server/explosion_callback.i

# target to preprocess a source file
src/server/explosion_callback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/explosion_callback.cpp.i
.PHONY : src/server/explosion_callback.cpp.i

src/server/explosion_callback.s: src/server/explosion_callback.cpp.s
.PHONY : src/server/explosion_callback.s

# target to generate assembly for a file
src/server/explosion_callback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/explosion_callback.cpp.s
.PHONY : src/server/explosion_callback.cpp.s

src/server/game_manager.o: src/server/game_manager.cpp.o
.PHONY : src/server/game_manager.o

# target to build an object file
src/server/game_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/game_manager.cpp.o
.PHONY : src/server/game_manager.cpp.o

src/server/game_manager.i: src/server/game_manager.cpp.i
.PHONY : src/server/game_manager.i

# target to preprocess a source file
src/server/game_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/game_manager.cpp.i
.PHONY : src/server/game_manager.cpp.i

src/server/game_manager.s: src/server/game_manager.cpp.s
.PHONY : src/server/game_manager.s

# target to generate assembly for a file
src/server/game_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/game_manager.cpp.s
.PHONY : src/server/game_manager.cpp.s

src/server/player_sender_thread.o: src/server/player_sender_thread.cpp.o
.PHONY : src/server/player_sender_thread.o

# target to build an object file
src/server/player_sender_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/player_sender_thread.cpp.o
.PHONY : src/server/player_sender_thread.cpp.o

src/server/player_sender_thread.i: src/server/player_sender_thread.cpp.i
.PHONY : src/server/player_sender_thread.i

# target to preprocess a source file
src/server/player_sender_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/player_sender_thread.cpp.i
.PHONY : src/server/player_sender_thread.cpp.i

src/server/player_sender_thread.s: src/server/player_sender_thread.cpp.s
.PHONY : src/server/player_sender_thread.s

# target to generate assembly for a file
src/server/player_sender_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/player_sender_thread.cpp.s
.PHONY : src/server/player_sender_thread.cpp.s

src/server/query_callback.o: src/server/query_callback.cpp.o
.PHONY : src/server/query_callback.o

# target to build an object file
src/server/query_callback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/query_callback.cpp.o
.PHONY : src/server/query_callback.cpp.o

src/server/query_callback.i: src/server/query_callback.cpp.i
.PHONY : src/server/query_callback.i

# target to preprocess a source file
src/server/query_callback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/query_callback.cpp.i
.PHONY : src/server/query_callback.cpp.i

src/server/query_callback.s: src/server/query_callback.cpp.s
.PHONY : src/server/query_callback.s

# target to generate assembly for a file
src/server/query_callback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/query_callback.cpp.s
.PHONY : src/server/query_callback.cpp.s

src/server/server_accept_thread.o: src/server/server_accept_thread.cpp.o
.PHONY : src/server/server_accept_thread.o

# target to build an object file
src/server/server_accept_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_accept_thread.cpp.o
.PHONY : src/server/server_accept_thread.cpp.o

src/server/server_accept_thread.i: src/server/server_accept_thread.cpp.i
.PHONY : src/server/server_accept_thread.i

# target to preprocess a source file
src/server/server_accept_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_accept_thread.cpp.i
.PHONY : src/server/server_accept_thread.cpp.i

src/server/server_accept_thread.s: src/server/server_accept_thread.cpp.s
.PHONY : src/server/server_accept_thread.s

# target to generate assembly for a file
src/server/server_accept_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_accept_thread.cpp.s
.PHONY : src/server/server_accept_thread.cpp.s

src/server/server_explosion.o: src/server/server_explosion.cpp.o
.PHONY : src/server/server_explosion.o

# target to build an object file
src/server/server_explosion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_explosion.cpp.o
.PHONY : src/server/server_explosion.cpp.o

src/server/server_explosion.i: src/server/server_explosion.cpp.i
.PHONY : src/server/server_explosion.i

# target to preprocess a source file
src/server/server_explosion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_explosion.cpp.i
.PHONY : src/server/server_explosion.cpp.i

src/server/server_explosion.s: src/server/server_explosion.cpp.s
.PHONY : src/server/server_explosion.s

# target to generate assembly for a file
src/server/server_explosion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_explosion.cpp.s
.PHONY : src/server/server_explosion.cpp.s

src/server/server_game.o: src/server/server_game.cpp.o
.PHONY : src/server/server_game.o

# target to build an object file
src/server/server_game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_game.cpp.o
.PHONY : src/server/server_game.cpp.o

src/server/server_game.i: src/server/server_game.cpp.i
.PHONY : src/server/server_game.i

# target to preprocess a source file
src/server/server_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_game.cpp.i
.PHONY : src/server/server_game.cpp.i

src/server/server_game.s: src/server/server_game.cpp.s
.PHONY : src/server/server_game.s

# target to generate assembly for a file
src/server/server_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_game.cpp.s
.PHONY : src/server/server_game.cpp.s

src/server/server_games_handler.o: src/server/server_games_handler.cpp.o
.PHONY : src/server/server_games_handler.o

# target to build an object file
src/server/server_games_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_games_handler.cpp.o
.PHONY : src/server/server_games_handler.cpp.o

src/server/server_games_handler.i: src/server/server_games_handler.cpp.i
.PHONY : src/server/server_games_handler.i

# target to preprocess a source file
src/server/server_games_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_games_handler.cpp.i
.PHONY : src/server/server_games_handler.cpp.i

src/server/server_games_handler.s: src/server/server_games_handler.cpp.s
.PHONY : src/server/server_games_handler.s

# target to generate assembly for a file
src/server/server_games_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_games_handler.cpp.s
.PHONY : src/server/server_games_handler.cpp.s

src/server/server_main.o: src/server/server_main.cpp.o
.PHONY : src/server/server_main.o

# target to build an object file
src/server/server_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_main.cpp.o
.PHONY : src/server/server_main.cpp.o

src/server/server_main.i: src/server/server_main.cpp.i
.PHONY : src/server/server_main.i

# target to preprocess a source file
src/server/server_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_main.cpp.i
.PHONY : src/server/server_main.cpp.i

src/server/server_main.s: src/server/server_main.cpp.s
.PHONY : src/server/server_main.s

# target to generate assembly for a file
src/server/server_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_main.cpp.s
.PHONY : src/server/server_main.cpp.s

src/server/server_player.o: src/server/server_player.cpp.o
.PHONY : src/server/server_player.o

# target to build an object file
src/server/server_player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_player.cpp.o
.PHONY : src/server/server_player.cpp.o

src/server/server_player.i: src/server/server_player.cpp.i
.PHONY : src/server/server_player.i

# target to preprocess a source file
src/server/server_player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_player.cpp.i
.PHONY : src/server/server_player.cpp.i

src/server/server_player.s: src/server/server_player.cpp.s
.PHONY : src/server/server_player.s

# target to generate assembly for a file
src/server/server_player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_player.cpp.s
.PHONY : src/server/server_player.cpp.s

src/server/server_protocol.o: src/server/server_protocol.cpp.o
.PHONY : src/server/server_protocol.o

# target to build an object file
src/server/server_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_protocol.cpp.o
.PHONY : src/server/server_protocol.cpp.o

src/server/server_protocol.i: src/server/server_protocol.cpp.i
.PHONY : src/server/server_protocol.i

# target to preprocess a source file
src/server/server_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_protocol.cpp.i
.PHONY : src/server/server_protocol.cpp.i

src/server/server_protocol.s: src/server/server_protocol.cpp.s
.PHONY : src/server/server_protocol.s

# target to generate assembly for a file
src/server/server_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_protocol.cpp.s
.PHONY : src/server/server_protocol.cpp.s

src/server/server_receiver_thread.o: src/server/server_receiver_thread.cpp.o
.PHONY : src/server/server_receiver_thread.o

# target to build an object file
src/server/server_receiver_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_receiver_thread.cpp.o
.PHONY : src/server/server_receiver_thread.cpp.o

src/server/server_receiver_thread.i: src/server/server_receiver_thread.cpp.i
.PHONY : src/server/server_receiver_thread.i

# target to preprocess a source file
src/server/server_receiver_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_receiver_thread.cpp.i
.PHONY : src/server/server_receiver_thread.cpp.i

src/server/server_receiver_thread.s: src/server/server_receiver_thread.cpp.s
.PHONY : src/server/server_receiver_thread.s

# target to generate assembly for a file
src/server/server_receiver_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_receiver_thread.cpp.s
.PHONY : src/server/server_receiver_thread.cpp.s

src/server/server_server.o: src/server/server_server.cpp.o
.PHONY : src/server/server_server.o

# target to build an object file
src/server/server_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_server.cpp.o
.PHONY : src/server/server_server.cpp.o

src/server/server_server.i: src/server/server_server.cpp.i
.PHONY : src/server/server_server.i

# target to preprocess a source file
src/server/server_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_server.cpp.i
.PHONY : src/server/server_server.cpp.i

src/server/server_server.s: src/server/server_server.cpp.s
.PHONY : src/server/server_server.s

# target to generate assembly for a file
src/server/server_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_server.cpp.s
.PHONY : src/server/server_server.cpp.s

src/server/trajectory_missile_callback.o: src/server/trajectory_missile_callback.cpp.o
.PHONY : src/server/trajectory_missile_callback.o

# target to build an object file
src/server/trajectory_missile_callback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/trajectory_missile_callback.cpp.o
.PHONY : src/server/trajectory_missile_callback.cpp.o

src/server/trajectory_missile_callback.i: src/server/trajectory_missile_callback.cpp.i
.PHONY : src/server/trajectory_missile_callback.i

# target to preprocess a source file
src/server/trajectory_missile_callback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/trajectory_missile_callback.cpp.i
.PHONY : src/server/trajectory_missile_callback.cpp.i

src/server/trajectory_missile_callback.s: src/server/trajectory_missile_callback.cpp.s
.PHONY : src/server/trajectory_missile_callback.s

# target to generate assembly for a file
src/server/trajectory_missile_callback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/trajectory_missile_callback.cpp.s
.PHONY : src/server/trajectory_missile_callback.cpp.s

src/server/world.o: src/server/world.cpp.o
.PHONY : src/server/world.o

# target to build an object file
src/server/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/world.cpp.o
.PHONY : src/server/world.cpp.o

src/server/world.i: src/server/world.cpp.i
.PHONY : src/server/world.i

# target to preprocess a source file
src/server/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/world.cpp.i
.PHONY : src/server/world.cpp.i

src/server/world.s: src/server/world.cpp.s
.PHONY : src/server/world.s

# target to generate assembly for a file
src/server/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/world.cpp.s
.PHONY : src/server/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client"
	@echo "... editor"
	@echo "... server"
	@echo "... level_editor/file_editor.o"
	@echo "... level_editor/file_editor.i"
	@echo "... level_editor/file_editor.s"
	@echo "... level_editor/level_editor.o"
	@echo "... level_editor/level_editor.i"
	@echo "... level_editor/level_editor.s"
	@echo "... level_editor/lobby.o"
	@echo "... level_editor/lobby.i"
	@echo "... level_editor/lobby.s"
	@echo "... level_editor/main.o"
	@echo "... level_editor/main.i"
	@echo "... level_editor/main.s"
	@echo "... level_editor/position_converter.o"
	@echo "... level_editor/position_converter.i"
	@echo "... level_editor/position_converter.s"
	@echo "... level_editor/world.o"
	@echo "... level_editor/world.i"
	@echo "... level_editor/world.s"
	@echo "... src/client/client_beam.o"
	@echo "... src/client/client_beam.i"
	@echo "... src/client/client_beam.s"
	@echo "... src/client/client_client.o"
	@echo "... src/client/client_client.i"
	@echo "... src/client/client_client.s"
	@echo "... src/client/client_explosion.o"
	@echo "... src/client/client_explosion.i"
	@echo "... src/client/client_explosion.s"
	@echo "... src/client/client_lobby.o"
	@echo "... src/client/client_lobby.i"
	@echo "... src/client/client_lobby.s"
	@echo "... src/client/client_main.o"
	@echo "... src/client/client_main.i"
	@echo "... src/client/client_main.s"
	@echo "... src/client/client_missile.o"
	@echo "... src/client/client_missile.i"
	@echo "... src/client/client_missile.s"
	@echo "... src/client/client_protocol.o"
	@echo "... src/client/client_protocol.i"
	@echo "... src/client/client_protocol.s"
	@echo "... src/client/client_receiver_thread.o"
	@echo "... src/client/client_receiver_thread.i"
	@echo "... src/client/client_receiver_thread.s"
	@echo "... src/client/client_resource_pool.o"
	@echo "... src/client/client_resource_pool.i"
	@echo "... src/client/client_resource_pool.s"
	@echo "... src/client/client_sender_thread.o"
	@echo "... src/client/client_sender_thread.i"
	@echo "... src/client/client_sender_thread.s"
	@echo "... src/client/client_worldview.o"
	@echo "... src/client/client_worldview.i"
	@echo "... src/client/client_worldview.s"
	@echo "... src/client/client_worm.o"
	@echo "... src/client/client_worm.i"
	@echo "... src/client/client_worm.s"
	@echo "... src/common/lib/liberror.o"
	@echo "... src/common/lib/liberror.i"
	@echo "... src/common/lib/liberror.s"
	@echo "... src/common/lib/resolver.o"
	@echo "... src/common/lib/resolver.i"
	@echo "... src/common/lib/resolver.s"
	@echo "... src/common/lib/resolvererror.o"
	@echo "... src/common/lib/resolvererror.i"
	@echo "... src/common/lib/resolvererror.s"
	@echo "... src/common/lib/socket.o"
	@echo "... src/common/lib/socket.i"
	@echo "... src/common/lib/socket.s"
	@echo "... src/server/baseball_bat_callback.o"
	@echo "... src/server/baseball_bat_callback.i"
	@echo "... src/server/baseball_bat_callback.s"
	@echo "... src/server/bodies/beam_body.o"
	@echo "... src/server/bodies/beam_body.i"
	@echo "... src/server/bodies/beam_body.s"
	@echo "... src/server/bodies/body.o"
	@echo "... src/server/bodies/body.i"
	@echo "... src/server/bodies/body.s"
	@echo "... src/server/bodies/missile_body.o"
	@echo "... src/server/bodies/missile_body.i"
	@echo "... src/server/bodies/missile_body.s"
	@echo "... src/server/bodies/worm_body.o"
	@echo "... src/server/bodies/worm_body.i"
	@echo "... src/server/bodies/worm_body.s"
	@echo "... src/server/broadcaster.o"
	@echo "... src/server/broadcaster.i"
	@echo "... src/server/broadcaster.s"
	@echo "... src/server/client_manager_thread.o"
	@echo "... src/server/client_manager_thread.i"
	@echo "... src/server/client_manager_thread.s"
	@echo "... src/server/contact_listener.o"
	@echo "... src/server/contact_listener.i"
	@echo "... src/server/contact_listener.s"
	@echo "... src/server/explosion_callback.o"
	@echo "... src/server/explosion_callback.i"
	@echo "... src/server/explosion_callback.s"
	@echo "... src/server/game_manager.o"
	@echo "... src/server/game_manager.i"
	@echo "... src/server/game_manager.s"
	@echo "... src/server/player_sender_thread.o"
	@echo "... src/server/player_sender_thread.i"
	@echo "... src/server/player_sender_thread.s"
	@echo "... src/server/query_callback.o"
	@echo "... src/server/query_callback.i"
	@echo "... src/server/query_callback.s"
	@echo "... src/server/server_accept_thread.o"
	@echo "... src/server/server_accept_thread.i"
	@echo "... src/server/server_accept_thread.s"
	@echo "... src/server/server_explosion.o"
	@echo "... src/server/server_explosion.i"
	@echo "... src/server/server_explosion.s"
	@echo "... src/server/server_game.o"
	@echo "... src/server/server_game.i"
	@echo "... src/server/server_game.s"
	@echo "... src/server/server_games_handler.o"
	@echo "... src/server/server_games_handler.i"
	@echo "... src/server/server_games_handler.s"
	@echo "... src/server/server_main.o"
	@echo "... src/server/server_main.i"
	@echo "... src/server/server_main.s"
	@echo "... src/server/server_player.o"
	@echo "... src/server/server_player.i"
	@echo "... src/server/server_player.s"
	@echo "... src/server/server_protocol.o"
	@echo "... src/server/server_protocol.i"
	@echo "... src/server/server_protocol.s"
	@echo "... src/server/server_receiver_thread.o"
	@echo "... src/server/server_receiver_thread.i"
	@echo "... src/server/server_receiver_thread.s"
	@echo "... src/server/server_server.o"
	@echo "... src/server/server_server.i"
	@echo "... src/server/server_server.s"
	@echo "... src/server/trajectory_missile_callback.o"
	@echo "... src/server/trajectory_missile_callback.i"
	@echo "... src/server/trajectory_missile_callback.s"
	@echo "... src/server/world.o"
	@echo "... src/server/world.i"
	@echo "... src/server/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

